### ISSUE TITLE
Implementation for different frameworks / languages

### ISSUE THREAD

**Issue by eyatzeck** [hamvocke/spring-testing#4]
I'm pretty agnostic, plus I don't mind there being a diversion in the discussion for people to let off steam, but I'm wondering if Spring is necessary, in the big picture.

**Comment by hamvocke** [comment]
Spring is not everyone's flavor, that's true. I already thought about implementing this entire testing stack for other frameworks: Rails or Django come to mind, maybe something in Golang, Kotlin, Clojure or Elixir would also be useful. I might just do that in the future (and make sure to extend the corresponding article so that you can choose your framework).

For now I lack the time to work on that directly but I'd be really happy to support anyone who wants to pick this up for any given language and framework.

I'll tag this issue accordingly, maybe we can find someone who wants to start on implementing the test pyramid for a different framework.

**Comment by israelconesa** [comment]
Hi @hamvocke, I enjoyed reading your article https://martinfowler.com/articles/practical-test-pyramid.html. With regards to the opening question; does the technology really matter here? It's about the concept of using different levels of testing. If the issue is of setting up, it could be facilitated using good old docker/docker-compose.
